name: w3_wallet
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  flutter_launcher_icons: ^0.10.0
  bruno: ^3.1.0
  url_launcher: ^6.1.6
  firebase_core: ^2.1.1
  auto_size_text: ^3.0.0
  flutter_spinkit: ^5.1.0
  card_swiper: ^2.0.4
  flutter_inappwebview: ^5.7.1+2
  webview_flutter: ^3.0.4
  polkawallet_sdk: ^0.5.1
  get_storage: ^2.0.3
  extended_text: ^9.1.2
  flutter_slidable: ^2.0.0
  dio: ^4.0.6
  decimal: ^2.3.2

flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/walletLogo.png"
  image_path_ios: "assets/images/walletLogo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/walletLogo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/walletLogo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/walletLogo.png"

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/web3games.png
    - assets/images/polkadot.png
    - assets/images/USDT.png
    - assets/images/bnb.png
    - assets/images/W3G.png
    - assets/images/icon-1024x1024.png
    - assets/images/APT.png
    - assets/images/bnb.png
    - assets/images/ETH.png
    - assets/images/GST.png
    - assets/images/aave.png
    - assets/images/bitcoin.png
    - assets/images/testimg.png
    - assets/images/logo.png
    - assets/images/page1.png
    - assets/images/page2.png
    - assets/images/page3.png
    - assets/images/success.png
    - assets/images/cryptoempire.png
    - assets/images/debeats.png
    - assets/images/w3poker.png
    - assets/images/walletLogo.png



