// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnMzO9Fip_-PSyIgjwlAau87L1gtVr74c',
    appId: '1:491532526871:web:be023cfce4dccae5624352',
    messagingSenderId: '491532526871',
    projectId: 'w3-wallet',
    authDomain: 'w3-wallet.firebaseapp.com',
    storageBucket: 'w3-wallet.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5CRUHmTWPcjTyRwBn1hb6v9TcSYQ0L0A',
    appId: '1:491532526871:android:a8be6cfd8c6eb13c624352',
    messagingSenderId: '491532526871',
    projectId: 'w3-wallet',
    storageBucket: 'w3-wallet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSKRY0PBctwiDr4MvhFnttAus3XbvJNzA',
    appId: '1:491532526871:ios:1b1c0b30df178534624352',
    messagingSenderId: '491532526871',
    projectId: 'w3-wallet',
    storageBucket: 'w3-wallet.appspot.com',
    iosClientId: '491532526871-ceupvp1hempma5q272jjpuooh6d99ckn.apps.googleusercontent.com',
    iosBundleId: 'com.web3games.wallet.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSKRY0PBctwiDr4MvhFnttAus3XbvJNzA',
    appId: '1:491532526871:ios:e175ad01b239eac2624352',
    messagingSenderId: '491532526871',
    projectId: 'w3-wallet',
    storageBucket: 'w3-wallet.appspot.com',
    iosClientId: '491532526871-4t30n813tm32i8q9smtl95n0cpr37glv.apps.googleusercontent.com',
    iosBundleId: 'web3games.w3Wallet',
  );
}
